version: '2'

services:
  xroad-soap-adapter:
    image: bthj/xroad-universal-soap
    ports:
      - "5080:5080"
      - "5443:5443"
    environment:
      KEY: "/etc/xroad-soap-adapter/xroad-soap-adapter.key"
      CERT: "/etc/xroad-soap-adapter/xroad-soap-adapter.crt"
    restart: always
    logging:
      driver: syslog
      options:
        tag: "xroad-soap-adapter"

  xroad-rest-adapter:
    image: bthj/xroad-rest-adapter-service
    ports:
      - "6080:8080"
    volumes:
      - /etc/rest-adapter-service:/etc/rest-adapter-service
    environment:
      - JAVA_OPTS=-DpropertiesDirectory=/etc/rest-adapter-service
    restart: always
    logging:
      driver: syslog
      options:
        tag: "xroad-rest-adapter"
